### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Ananyapam7** [monoid/starjs#4]
Hi!
StarJs looks like an amazing library for Javascript, however it does not have the requisite documentation to help users harness it fully. It'll be great if there can be some sort of user guide/ documentation/ sample codes etc. Thanks in advance.

**Comment by monoid** [comment]
Hi! Indeed, the library has no documentation.  However, one can use 'Astronomy on the Personal Computer' by O. Montenbrook and T. Pfleger as a reference: this JavaScript library is based on this book (I used 4th edition, but there shouldn't be a big difference).

There is also canvas-based planetarium that uses the StarJs: https://github.com/monoid/starchartjs/blob/master/starmap.js

I close this issue in favor of #1.

**Comment by monoid** [comment]
@Ananyapam7 BTW look at the `examples` directory: it has some comments that may help you.
